name: Build size-optimized binary
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - name: Linux x86_64
          os: ubuntu-latest
          target: x86_64-unknown-linux-gnu
        - name: macOS x86_64
          os: macos-latest
          target: x86_64-apple-darwin
        - name: Windows x86_64
          os: windows-latest
          target: x86_64-pc-windows-msvc
    name: Build ${{ matrix.name }}
    steps:
      - uses: actions/checkout@v3
      - run: rustup update nightly && rustup default nightly
      - run: rustup target add ${{ matrix.target }}
      - run: rustup component add rust-src --toolchain nightly
      - run: cargo +nightly build -Z build-std=std,panic_abort -Z build-std-features=panic_immediate_abort --target ${{ matrix.target }} --release
        name: build
      - uses: actions/upload-artifact@v3
        with:
          name: scratch-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/scratch
          retention-days: 1